### PR TITLE
Fix container not restarting once stopped when started as local user

### LINKED ISSUE #47: Composer won't start again when COMPOSER_CONTAINER_RUN_AS_HOST_USER
I'm using the latest version (eacc17c2c934b7873b7302f4d6b2dd9bdaf6d9d8).

The first time Composer starts, everything is working fine. But if I stop it, and start it again, it doesn't work any more. Here are the final logs the container gives:

```
$ docker container logs composer-local-dev-my-composer 
...
+ run_airflow_as_host_user
+ create_user nicolas 1000
+ local user_name=nicolas
+ local user_id=1000
+ local old_user_name
+ whoami
+ old_user_name=airflow
+ local old_user_id
+ id -u
+ old_user_id=999
+ echo Adding user nicolas(1000)
+ sudo useradd -m -r -g airflow -G airflow --home-dir /home/airflow -u 1000 -o nicolas
Adding user nicolas(1000)
useradd: user 'nicolas' already exists
```

### PR DESCRIPTION
**Pull request by nbonnotte**
Fix #47

When running as local user with COMPOSER_CONTAINER_RUN_AS_HOST_USER,
- Allow Composer to restart
- Allow user to run airflow command

### CODE REVIEW

**Comment by ahidalgob** [comment]
Hi, thank you for your PR @nbonnotte,

In terms of maintainability and trying to keep the code cleaner, I think if we could not dynamically generate the `run` script but have a static script that checks this environment variable and runs the passed command accordingly it would be better. Since this variable is exported I think it should be available in the `env`.

**Comment by nbonnotte** [comment]
Hi @ahidalgob 

Good idea! I've just pushed a new commit to add that static script. Let me know what you think

**Comment by gitmstoute** [comment]
Just chiming in to say, I installed this branch and it resolved several issues I was having with `0.9.2` from pypi, including  `airflow.db` being `readonly` to the airflow process and container not restarting. Thank you for the commit @nbonnotte , hopefully it can be merged quickly!

**Review by ahidalgob — CHANGES_REQUESTED** [review]
LGTM but please switch the destination branch from main to development and I will merge right away:)

**Comment by nbonnotte** [comment]
@ahidalgob I've switched to `development` :smile:

**Comment by nbonnotte** [comment]
@ahidalgob I've solved the conflicts :smile:

**Pull request merged**
