### PR TITLE
Fix running Composer as host user

### PR DESCRIPTION
**Pull request by nbonnotte**
Edited: merge of #48 and #49

### CODE REVIEW

**Comment by nbonnotte** [comment]
Unfortunately the `run-airflow-cmd` command does not work any more, because the command is still being executed as `airflow` :cry:

**Comment by nbonnotte** [comment]
The last commit
- adds a `run` as a shorthand for `sudo -u localuser env PATH=....`
- refactors the entrypoint to use it
- fixes `run_airflow_command` by using it as well

**Comment by nbonnotte** [comment]
Well it seems I never needed to do anything special to keep the `ENV` variable :thinking: 

Maybe I got confused when I added it to `variables.env` and forgot to recreate the container? :shrug:

**Comment by nbonnotte** [comment]
I've splitted the PR into #48 and #49

**Comment by ahidalgob** [comment]
Answered on the separate PRs, shall we close this one?

**Pull request closed without merging**
